# Numpy

- NumPy is a general-purpose array-processing package.
- Numpy was created to work with multidmensional arrays.
- It is the fundamental package for scientific computing with Python.
- It is open-source library.

# Why Use NumPy?
- In Python we have lists that serve the purpose of arrays, but they are slow to process.

- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

- The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

- Arrays are very frequently used in data science, where speed and resources are very important.

In [1]:
#Importing necessary library

!pip install numpy

In [1]:
import numpy as np

In [2]:
#Array Creation

In [11]:
a = np.array([1,2,3,4,5])
print(a)
type(a)
a.ndim

[1 2 3 4 5]


1

In [10]:
#Zero dimensional array

In [18]:
z = np.array(10)
print(z.ndim)
type(z)

0


numpy.ndarray

In [11]:
#One dimensional array

In [17]:
a = np.array([1,2,3,4,5])
a.ndim

1

In [12]:
#Two dimensional array

In [19]:
t = np.array([[1,2,3,4,5]])
print(t)
print(t.ndim)

[[1 2 3 4 5]]
2


In [13]:
#Three dimensional array

In [20]:
b = np.array([[[1,2,3,4,5]]])
print(b)
print(b.ndim)

[[[1 2 3 4 5]]]
3


In [9]:
#Change the data type of the array elements.

In [23]:
a = np.array([[1.0,2.0,3.0,4.0,5.0]], dtype = 'int' )
a

array([[1, 2, 3, 4, 5]])

# Other ways of creating an array
1. arange
2. linspace
3. zeros
4. ones

In [27]:
a = np.arange(500,1000)
a

array([500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512,
       513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525,
       526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538,
       539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551,
       552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564,
       565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577,
       578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590,
       591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603,
       604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616,
       617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629,
       630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642,
       643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655,
       656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668,
       669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 68

In [30]:
l = np.linspace(1,20,25, retstep=True)
l

(array([ 1.        ,  1.79166667,  2.58333333,  3.375     ,  4.16666667,
         4.95833333,  5.75      ,  6.54166667,  7.33333333,  8.125     ,
         8.91666667,  9.70833333, 10.5       , 11.29166667, 12.08333333,
        12.875     , 13.66666667, 14.45833333, 15.25      , 16.04166667,
        16.83333333, 17.625     , 18.41666667, 19.20833333, 20.        ]),
 0.7916666666666666)

In [33]:
z = np.zeros([2,2])

z

array([[0., 0.],
       [0., 0.]])

In [35]:
o = np.ones([2,2])
o

array([[1., 1.],
       [1., 1.]])

# Slicing and Indexing of arrays

In [8]:
a = np.array([[1,2,3],[7,8,9]])
a

array([[1, 2, 3],
       [7, 8, 9]])

In [38]:
a[0,0]

1

In [39]:
a[1,2]

9

In [40]:
a[:,1:]

array([[2, 3],
       [8, 9]])

In [41]:
a[0,1:]

array([2, 3])

In [4]:
a

array([[1, 2, 3],
       [7, 8, 9]])

In [9]:
a[[0,0],[1,2]]

array([2, 3])

In [10]:
a[[0,1],[0,2]]

array([1, 9])

# Aggregate Functions

- The Python numpy aggregate functions are sum, min, max, mean, average, product, median, standard deviation, variance,  percentile, and corrcoef.

In [11]:
a = np.array([1,2,3,4,5])

In [12]:
a.sum()

15

In [14]:
a.min()

1

In [15]:
a.max()

5

In [17]:
a.mean()

3.0

In [18]:
a.std()

1.4142135623730951

# Stacking 
- Stacking is used to join 2 different arrays.
- Vertical stacking
- Horizontal stacking

In [23]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [22]:
c = np.vstack([a,b])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
d = np.hstack([a,b])

In [25]:
d

array([1, 2, 3, 4, 5, 6])